package com.hft.model.enums;

/**
 * Trading signal generated by the recommendation engine.
 * Score thresholds defined in SignalGeneratorService.
 */
public enum SignalType {
    STRONG_BUY  ("Strong Buy",  "🔥", 80, 100, true),
    BUY         ("Buy",         "✅", 65,  79, true),
    HOLD        ("Hold",        "⏸️", 45,  64, false),
    SELL        ("Sell",        "❌", 30,  44, false),
    STRONG_SELL ("Strong Sell", "💀",  0,  29, false),
    WATCH       ("Watch List",  "👀", 55,  64, false);  // near-buy zone

    private final String displayName;
    private final String emoji;
    private final int minScore;
    private final int maxScore;
    private final boolean isBullish;

    SignalType(String displayName, String emoji, int minScore, int maxScore, boolean isBullish) {
        this.displayName = displayName;
        this.emoji = emoji;
        this.minScore = minScore;
        this.maxScore = maxScore;
        this.isBullish = isBullish;
    }

    public String getDisplayName() { return displayName; }
    public String getEmoji()       { return emoji; }
    public int getMinScore()       { return minScore; }
    public int getMaxScore()       { return maxScore; }
    public boolean isBullish()     { return isBullish; }

    public static SignalType fromScore(double score) {
        if (score >= 80) return STRONG_BUY;
        if (score >= 65) return BUY;
        if (score >= 55) return WATCH;
        if (score >= 45) return HOLD;
        if (score >= 30) return SELL;
        return STRONG_SELL;
    }
}